Repository H-uru/Plasma, pull requests merged in 2020-07, with the labels that each got.

#681 Add dice commands to KI chat.
  Scripts/Python/ki/xKIChat.py
  Scripts/Python/ki/xKIConstants.py
Labels: Enhancement

#685 Handle font characters with negative baselines
  Sources/Plasma/PubUtilLib/plGImage/plFont.cpp
Labels: 64-bit compatibility

#694 Fix typo in KI chat dice roll message.
  Scripts/Python/ki/xKIChat.py
Labels: Client, Defect
