Repository H-uru/Plasma, pull requests merged in 2022-12, with the labels that each got.

#1194 Add capability to use a sliding solution window for puzzle buttons
  Scripts/Python/xAgeSDLBoolActivatorComboSet.py
  Scripts/SDL/xAgeSDLBoolActivatorComboSet.sdl
  Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifier.cpp
Labels: Client, Enhancement, Blocking on MOULa

#1242 Ahnonay Cathedral Q3 2022 Update
  Scripts/SDL/ahnonaycathedral.sdl
Labels: Blocking on MOULa, Content

#1270 Additional Cyan Trailer Cameras
  Scripts/Python/city.py
  Scripts/dat/Garden.age
  Scripts/dat/Neighborhood.age
  Scripts/dat/Personal.age
  Scripts/dat/Teledahn.age
Labels: Content
