Repository H-uru/Plasma, pull requests merged in 2022-04, with the labels that each got.

#1116 Prevent unicode decode errors when hovering BigKI menu items
  Scripts/Python/ki/__init__.py
Labels: Defect

#1117 Short-circuit setting KI font size when new size is same as current size
  Scripts/Python/ki/__init__.py
Labels: Client, Enhancement

#1103 Don't feed remaining subtitles when audio skips to past the end of last subtitle
  Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp
  Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.cpp
  Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.h
Labels: Client, Defect

#1119 Fix even moar Chinese.
  Sources/Tools/MaxComponent/plResponderComponent.cpp
  Sources/Tools/MaxMain/plAgeDescInterface.cpp
Labels: Plugin, Defect

#1057 Allow disabling panic linking.
  Scripts/Python/plasma/Plasma.py
  Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.cpp
  Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.h
  Sources/Plasma/FeatureLib/pfPython/cyAvatar.cpp
  Sources/Plasma/FeatureLib/pfPython/cyAvatar.h
  Sources/Plasma/FeatureLib/pfPython/cyAvatarGlue.cpp
  Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
  Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h
Labels: Client, Enhancement, Python

#1050 Cleft Start option added
  Scripts/Python/Cleft.py
  Scripts/Python/Personal.py
  Scripts/Python/clftGetPersonalBook.py
  Scripts/Python/clftImager.py
  Scripts/Python/ki/__init__.py
  Scripts/Python/xAvatarCustomization.py
  Scripts/Python/xDialogStartUp.py
  Scripts/Python/xOpeningSequence.py
  Scripts/Python/xStartPathHelpers.py
  Scripts/Python/xYeeshaPages.py
  Scripts/dat/StartUp.fni
Labels: Client, Enhancement

#1053 Files for Backpack and Backpack2 collectibles
  Scripts/SDL/Dereno.sdl
  Scripts/dat/Dereno.age
  Scripts/dat/Ercana.age
Labels: Blocking on MOULa

#1097 Prevent deferred link race conditions.
  Sources/Plasma/PubUtilLib/plNetClient/plNetLinkingMgr.cpp
Labels: Client, Defect

#1108 Remove foreign swear words from the censor.
  Scripts/Python/xCensorFilters.py
Labels: Defect

#1111 Add v28 to Garrison.sdl for renamed duplicate variable
  Scripts/SDL/Garrison.sdl
Labels: Defect

#1098 Add margins to KI chat display to fix shadow clipping.
  Scripts/Python/ki/__init__.py
  Scripts/Python/plasma/Plasma.py
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp
Labels: Client, Defect, Python

#1091 Add Python Scripts Verification to CI.
  .github/scripts_matchers.json
  .github/workflows/scripts_review.yml
  Scripts/Python/mymod.py
  Scripts/Python/plasma/Plasma.py
  Scripts/Tests/xGamePythonReview.py
Labels: Enhancement, Python

#1133 Fix 3dsMax crash caused by Garrison Wall.
  Scripts/Python/grsnWallEventHandler.py
Labels: Plugin, Defect, Python

#1100 Fix KI chat not wrapping correctly after size change.
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp
Labels: Client, Defect

#1138 Fix missing module problem in scripts review.
  Scripts/Tests/xGamePythonReview.py
Labels: Defect

#1130 Update Nexus Scripts for public GoMePubNew
  Scripts/Python/islmRegisterNexusLink.py
  Scripts/Python/nxusBookMachine.py
Labels: Enhancement
