Repository H-uru/Plasma, pull requests merged in 2022-05, with the labels that each got.

#1139 Fix for divide by zero breaking Mac/Vee Tsah
  Sources/Plasma/PubUtilLib/plSurface/plShader.cpp
Labels: Client, Defect

#1140 Ensure emotes and afk message are shown in receiver's localization
  Scripts/Python/ki/__init__.py
  Scripts/Python/ki/xKIChat.py
  Scripts/Python/ki/xKIHelpers.py
  Scripts/Python/plasma/PlasmaKITypes.py
  Scripts/Python/xLocTools.py
  Sources/Plasma/FeatureLib/pfMessage/pfKIMsg.h
Labels: Enhancement

#1141 Save and load the user's /textcolor setting to persist it between game sessions
  Scripts/Python/ki/__init__.py
  Scripts/Python/ki/xKIChat.py
  Scripts/Python/plasma/PlasmaKITypes.py
Labels: Enhancement

#1148 Fix Kveer was registering itself as a city link
  Scripts/Python/islmRegisterNexusLink.py
Labels: Defect

#1151 Fix so chat logs don't duplicate every line
  Scripts/Python/ki/xKIChat.py
Labels: Defect

#1152 Fix my dumb so /textcolor 999 won't try to convert None to int and die
  Scripts/Python/ki/xKIChat.py
Labels: Defect

#1143 Allow `ptVaultNode.findNode()` to search deeper than one level.
  Scripts/Python/plasma/Plasma.py
  Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp
  Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
  Sources/Plasma/FeatureLib/pfPython/pyVaultNode.h
  Sources/Plasma/FeatureLib/pfPython/pyVaultNodeGlue.cpp
Labels: Client, Enhancement, Python

#1142 Fixes wrong Ahnonay instance bug
  Scripts/Python/Ahnonay.py
  Scripts/Python/AhnonayCathedral.py
Labels: Defect

#1154 Climb Brain crash fix
  Sources/Plasma/PubUtilLib/plAvatar/plAvBrainClimb.cpp
Labels: Defect

#1157 Don't build libuuid on macOS with vcpkg.
  vcpkg.json
Labels: Defect

#1153 Fix pod portal responder for multiplayer
  Scripts/Python/xPodBahroSymbol.py
Labels: Defect

#1163 Ensure providing current folder name for delete player localized message
  Scripts/Python/ki/__init__.py
Labels: Defect

#1168 Ahnonay script crashing
  Scripts/Python/Ahnonay.py
Labels: Defect

#1171 `ST::string`-ize `pfGUIControlTextBox`.
  Sources/Plasma/FeatureLib/pfCharacter/pfConfirmationMgr.cpp
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBoxGlue.cpp
  Sources/Tools/MaxComponent/plGUIComponents.cpp
Labels: Client

#1173 Reformat HTML Console documentation output
  Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
  Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.cpp
Labels: Client, Enhancement

#1176 Prevent python errors on startup dialog with empty explorer list
  Scripts/Python/xDialogStartUp.py
Labels: Defect

#1172 Support create player with unicode name and fix a bunch of string-murdering
  Scripts/Python/ki/__init__.py
  Scripts/Python/xDialogStartUp.py
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListBoxMod.cpp
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListBoxMod.h
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListElement.cpp
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListElement.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBoxGlue.cpp
Labels: Defect

#1162 Add prefix to chat logs, plus to chat headers when /textcolor is enabled
  Scripts/Python/ki/xKIChat.py
Labels: Client, Enhancement

#1175 Sort clothing in closet and fix clothing resetting when clicking on arrows
  Scripts/Python/xAvatarCustomization.py
Labels: Defect

#1155 Fix method name collisions in `ptVaultTextNoteNode`.
  Scripts/Python/plasma/Plasma.py
  Sources/Plasma/FeatureLib/pfPython/pyVaultTextNoteNodeGlue.cpp
Labels: Client, Defect, Python

#1123 Add clipboard support to the console.
  Sources/Plasma/FeatureLib/pfConsole/CMakeLists.txt
  Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
  Sources/Plasma/FeatureLib/pfConsole/pfConsole.h
  Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp
Labels: Enhancement
