Repository H-uru/Plasma, pull requests merged in 2022-02, with the labels that each got.

#973 K'veer Update August 2021
  Scripts/SDL/Kveer.sdl
Labels: Blocking on MOULa

#1070 Squelch script ID warnings in 3ds Max.
  Scripts/Python/Tiam.py
  Scripts/Python/Vothol.py
  Scripts/Python/trebivdil.py
Labels: Python

#1069 Fix max crash on exit.
  Sources/Tools/MaxComponent/plAutoUIBase.cpp
  Sources/Tools/MaxComponent/plPythonFileComponent.cpp
Labels: Plugin

#1068 Fix 3dsMax python parameters.
  Sources/Tools/MaxComponent/plAutoUIBase.cpp
Labels: Plugin

#1080 Fix compatibility with CMake older than 3.18
  cmake/Findexpat.cmake
  cmake/Findfreetype.cmake
Labels: Defect
