Repository H-uru/Plasma, pull requests merged in 2022-08, with the labels that each got.

#1146 Update Chiso scripts
  Scripts/SDL/ChisoPreniv.sdl
  Scripts/dat/ChisoPreniv.age
Labels: Enhancement, Blocking on MOULa, Content

#1181 Mysterium Tshirts files
  Scripts/dat/GlobalClothing.age
Labels: Content

#1186 Tiam Q2 2022 Update
  Scripts/SDL/Tiam.sdl
Labels: Blocking on MOULa, Content

#1215 Update GoMePubNew Q2 2022
  Scripts/SDL/GoMePubNew.sdl
  Scripts/dat/GoMePubNew.age
Labels: Blocking on MOULa

#1177 Add Highgarden AGE and FNI
  Scripts/dat/FahetsHighgarden.age
  Scripts/dat/FahetsHighgarden.fni
Labels: Enhancement, Blocking on MOULa, Content
