Repository H-uru/Plasma, pull requests merged in 2022-06, with the labels that each got.

#1150 Fix issue with TPOTS code and Relto start
  Scripts/Python/clftImager.py
Labels: Defect

#1024 Better Crash Dialog (Part 1)
  CMakeLists.txt
  Sources/Plasma/Apps/plClient/winmain.cpp
  Sources/Plasma/Apps/plCrashHandler/CMakeLists.txt
  Sources/Plasma/Apps/plCrashHandler/Dirt.ico
  Sources/Plasma/Apps/plCrashHandler/banner.bmp
  Sources/Plasma/Apps/plCrashHandler/plCrashHandler.exe.manifest
  Sources/Plasma/Apps/plCrashHandler/plCrashHandler.rc
  Sources/Plasma/Apps/plCrashHandler/resource.h
  Sources/Plasma/Apps/plCrashHandler/winmain.cpp
  Sources/Plasma/FeatureLib/pfCrashHandler/CMakeLists.txt
  Sources/Plasma/FeatureLib/pfCrashHandler/plCrashCli.cpp
  Sources/Plasma/FeatureLib/pfCrashHandler/plCrashCli.h
  Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.cpp
  Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.h
  Sources/Plasma/FeatureLib/pfCrashHandler/plCrash_Private.h
  Sources/Plasma/FeatureLib/pfCrashHandler/plNullStackWalker.cpp
  Sources/Plasma/FeatureLib/pfCrashHandler/plStackWalker.h
  Sources/Plasma/FeatureLib/pfCrashHandler/plWindowsStackWalker.cpp
Labels: Client, Enhancement

#1183 Increase font size on AtrusNote for better resolution
  Scripts/Python/xDynTextDefs.py
Labels: Enhancement

#1076 Better user data paths on non-Windows
  Sources/Plasma/CoreLib/HeadSpin.h
  Sources/Plasma/CoreLib/hsThread_Unix.cpp
  Sources/Plasma/CoreLib/plFileSystem.cpp
  Sources/Tools/plSystemInfo/main.cpp
Labels: Porting, Enhancement
