Repository H-uru/Plasma, pull requests merged in 2022-03, with the labels that each got.

#1092 Automatically find clang-tidy when using VS.
  cmake/Sanitizers.cmake
Labels: Enhancement

#1099 Improve `std::wstring` copying in `pfGUITextBoxMod`.
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp
Labels: Client

#1063 Add audio.ini EnableSubtitles option and support to display timed subtitles in the KI
  Scripts/Python/ki/__init__.py
  Scripts/Python/ki/xKIChat.py
  Scripts/Python/ki/xKIConstants.py
  Scripts/Python/plasma/Plasma.py
  Scripts/Python/plasma/PlasmaKITypes.py
  Scripts/Python/xIniAudio.py
  Sources/Plasma/Apps/plClient/plClient.cpp
  Sources/Plasma/CoreLib/hsStream.cpp
  Sources/Plasma/CoreLib/hsStream.h
  Sources/Plasma/FeatureLib/pfConsole/pfAudioConsoleCommands.cpp
  Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
  Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.h
  Sources/Plasma/FeatureLib/pfPython/pyAudioControl.cpp
  Sources/Plasma/FeatureLib/pfPython/pyAudioControl.h
  Sources/Plasma/FeatureLib/pfPython/pyAudioControlGlue.cpp
  Sources/Plasma/NucleusLib/inc/plCreatableIndex.h
  Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.cpp
  Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.h
  Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp
  Sources/Plasma/PubUtilLib/plAudioCore/CMakeLists.txt
  Sources/Plasma/PubUtilLib/plAudioCore/plSoundBuffer.cpp
  Sources/Plasma/PubUtilLib/plAudioCore/plSoundBuffer.h
  Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.cpp
  Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.h
  Sources/Plasma/PubUtilLib/plMessage/CMakeLists.txt
  Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h
  Sources/Plasma/PubUtilLib/plMessage/plSubtitleMsg.h
Labels: Client, Enhancement

#1101 Fix moar Max `char*` being reinterpreted as `wchar_t*`.
  Sources/Tools/MaxComponent/plGUIComponents.cpp
Labels: Plugin, Defect

#1102 Fix moar Max plugin crashes.
  Sources/Tools/MaxComponent/plAnimCompProc.cpp
  Sources/Tools/MaxComponent/plAnimComponent.cpp
  Sources/Tools/MaxComponent/plGUIComponents.cpp
  Sources/Tools/MaxComponent/plNotetrackDlg.cpp
  Sources/Tools/MaxComponent/plNotetrackDlg.h
  Sources/Tools/MaxComponent/plResponderAnim.cpp
  Sources/Tools/MaxComponent/plResponderMtl.cpp
  Sources/Tools/MaxPlasmaMtls/Materials/plAnimStealthNode.cpp
Labels: Plugin, Defect

#1105 Re-add stale Python attributes.
  Scripts/Python/ki/__init__.py
  Scripts/Python/xOptionsMenu.py
Labels: Plugin, Defect, Python

#1106 Fix crash when `plClipboard::SetClipboardText()` is called twice.
  Sources/Plasma/CoreLib/hsWindows.h
  Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp
Labels: Client, Defect

#1096 Options menu support for enabling/disabling subtitles
  Scripts/Python/xOptionsMenu.py
  Sources/Plasma/Apps/plClient/plClient.cpp
  Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.cpp
  Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp
Labels: Client, Enhancement

#1107 Allow clickable URLs to begin with "www."
  Scripts/Python/xGUILinkHandler.py
Labels: Client, Enhancement

#1110 Fix errors when HAVE_CPUID is false
  Sources/Plasma/CoreLib/hsSystemInfo.cpp
Labels: Defect
