Repository H-uru/Plasma, pull requests merged in 2022-07, with the labels that each got.

#1211 Init large arrays on heap instead of stack in font creation
  Sources/Tools/plFontConverter/plFontFreeType.cpp
Labels: Tools, Defect

#1159 Code for static imager image to show in imager slides
  Scripts/Python/xSimpleImager.py
  Scripts/Python/xSimpleImagerClueHandler.py
Labels: Enhancement

#1127 Revert to PhysX CCT.
  Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.cpp
  Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.h
  Sources/Plasma/PubUtilLib/plPhysX/CMakeLists.txt
  Sources/Plasma/PubUtilLib/plPhysX/plKickableLog.cpp
  Sources/Plasma/PubUtilLib/plPhysX/plKickableLog.h
  Sources/Plasma/PubUtilLib/plPhysX/plPXConvert.h
  Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp
  Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.h
  Sources/Plasma/PubUtilLib/plPhysX/plPXSimulation.cpp
  Sources/Plasma/PubUtilLib/plPhysX/plPXSimulation.h
Labels: Client, Defect
