Repository H-uru/Plasma, pull requests merged in 2023-07, with the labels that each got.

#1418 Specify older Pillow version to fix cairosvg build
  Scripts/Ports/python3-cairosvg/portfile.cmake
  Scripts/Ports/python3-cairosvg/vcpkg.json
Labels: CI / Build

#1428 `ptGUIControl` construction improvement.
  Scripts/Python/clftYeeshaPage08.py
  Scripts/Python/ercaOvenScope.py
  Scripts/Python/grtzMarkerScopeGUI.py
  Scripts/Python/ki/xKIChat.py
  Scripts/Python/nxusBookMachine.py
  Scripts/Python/plasma/Plasma.py
  Scripts/Python/tldnPwrTwrPeriscope.py
  Scripts/Python/tldnVaporScope.py
  Scripts/Python/xAvatarCustomization.py
  Scripts/Python/xDialogClothingBB.py
  Scripts/Python/xDialogStartUp.py
  Scripts/Python/xOpeningSequence.py
  Scripts/Python/xOptionsMenu.py
  Scripts/Python/xYeeshaPages.py
  Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogMod.h
  Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlButton.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlButton.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlCheckBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlCheckBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlClickMap.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlClickMap.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlDynamicText.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlDynamicText.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlRadioGroup.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlRadioGroup.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlValue.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIControlValue.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIDialog.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIDialog.h
  Sources/Plasma/FeatureLib/pfPython/pyGUIDialogGlue.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIPopUpMenu.cpp
  Sources/Plasma/FeatureLib/pfPython/pyGUIPopUpMenu.h
Labels: Client, Python

#1436 Fix footstep sounds being in Chinese.
  Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.cpp
  Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h
  Sources/Tools/MaxComponent/plFootstepComponent.cpp
  Sources/Tools/MaxComponent/plResponderLink.cpp
Labels: Plugin

#1440 Audit all `ComboBox_AddString` macro calls.
  Sources/Tools/MaxComponent/plAnimCompProc.cpp
  Sources/Tools/MaxComponent/plClimbComponent.cpp
  Sources/Tools/MaxComponent/plNavigableComponents.cpp
  Sources/Tools/MaxComponent/plResponderAnim.cpp
  Sources/Tools/MaxComponent/plResponderMtl.cpp
  Sources/Tools/MaxComponent/plTypesComponents.cpp
  Sources/Tools/MaxMain/plTextureSearch.cpp
Labels: Plugin
